### ISSUE TITLE
Data Visualization: UW Alert Map heat map visualization

### ISSUE THREAD

**Issue by evanyfyip** [evanyfyip/uw-alert-web#3]
**Goal:** Visualize the most prominent/dangerous parts of Udistrict on a map
- Use a heatmap and size of markers to represent more incidents

**Comment by jamesjoko** [comment]
A basic heatmap is currently implemented into the get_folium_map function. I will update the code accordingly when we determine an urgency mechanic. I think it is unlikely for two alerts to be in the same location, UW edits alerts with updates instead of sending out another alert.
