### ISSUE TITLE
Data Visualization: UW Alert Real-time street alert

### ISSUE THREAD

**Issue by evanyfyip** [evanyfyip/uw-alert-web#4]
**Goal:** Build a visualization that highlights the current street with a potential threat
- Includes interactive tooltip describing the event
- Includes original uw alert description

**Comment by jamesjoko** [comment]
get_folium_map has two parameters: alert_coords, a List of List containing two floats to represent alert coordinates, and alert_messages, a List of Strings corresponding to alert_coords with the UW Alert Description, which is then put into an IFrame popup of a marker.

**Comment by mtqiao4** [comment]
additionally add a data structure that keeps track of each individual marker made so that its text can be dynamically updated within the html front end

**Comment by jamesjoko** [comment]
> 

Added in newest PR.
