### ISSUE TITLE
Real time input interface

### ISSUE THREAD

**Issue by evanyfyip** [evanyfyip/uw-alert-web#5]
**Goal:** Build a realtime input interface for UW Alerts to input alert and generate a visualization
- Can either parse the realtime text
- Can be a json file input
- Can be something else

**Comment by mtqiao4** [comment]
Visualization interface through flask has been created. 

TODO: Build realtime text parser

**Comment by mtqiao4** [comment]
Text parser has been created, now needs to be implemented using some server/client technology.
TODO: Use either AJAX, JQuery, or Socket to implement a constant call to the server in order to scrape the text and update map based on new updates.
